---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kutt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kutt
  template:
    metadata:
      labels:
        app: kutt
    spec:
      imagePullSecrets:
        - name: github-registry-secret
      containers:
      - name: web
        image: kutt/kutt
        ports:
        - containerPort: 3000
          protocol: TCP
        command: ["node"]
        args: ["production-server/server.js"]
        readinessProbe:
          httpGet:
            path: /api/v2/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/v2/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: CONTACT_EMAIL
          valueFrom:
            configMapKeyRef:
              name: kutt
              key: contact-email
        - name: CUSTOM_DOMAIN_USE_HTTPS
          valueFrom:
            configMapKeyRef:
              name: kutt
              key: domain-https
        - name: DEFAULT_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: kutt
              key: domain
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_ENV
          valueFrom:
            configMapKeyRef:
              name: kutt
              key: node-env
        - name: DD_LOGS_INJECTION
          valueFrom:
            configMapKeyRef:
              name: kutt
              key: dd-logs-injection
        - name: DD_SERVICE
          valueFrom:
            configMapKeyRef:
              name: kutt
              key: domain
        - name: DD_PROFILING_ENABLED
          valueFrom:
            configMapKeyRef:
              name: kutt
              key: dd-profiling
        - name: DD_RUNTIME_METRICS_ENABLED
          valueFrom:
            configMapKeyRef:
              name: kutt
              key: dd-runtime-metrics
        - name: DD_TRACE_ANALYTICS_ENABLED
          valueFrom:
            configMapKeyRef:
              name: kutt
              key: dd-trace-analytics
        - name: DISALLOW_ANONYMOUS_LINKS
          valueFrom:
            configMapKeyRef:
              name: kutt
              key: disallow-anonymous
        - name: DISALLOW_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: kutt
              key: disallow-domain
        - name: DISALLOW_REGISTRATION
          valueFrom:
            configMapKeyRef:
              name: kutt
              key: disallow-reg
        - name: LINK_LENGTH
          valueFrom:
            configMapKeyRef:
              name: kutt
              key: link-length
        - name: MAIL_PORT
          valueFrom:
            configMapKeyRef:
              name: kutt
              key: mail-port
        - name: MAIL_SECURE
          valueFrom:
            configMapKeyRef:
              name: kutt
              key: mail-secure
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: kutt
              key: node-env
        - name: REDIS_DB
          valueFrom:
            configMapKeyRef:
              name: kutt
              key: redis-db
        - name: REPORT_EMAIL
          valueFrom:
            configMapKeyRef:
              name: kutt
              key: report-email
        - name: SITE_NAME
          valueFrom:
            configMapKeyRef:
              name: kutt
              key: site-name
        - name: USER_LIMIT_PER_DAY
          valueFrom:
            configMapKeyRef:
              name: kutt
              key: user-limit
        - name: ADMIN_EMAILS
          valueFrom:
            secretKeyRef:
              name: kutt
              key: admin-emails
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: kutt
              key: db-host
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: kutt
              key: db-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: kutt
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kutt
              key: db-password
        - name: GOOGLE_SAFE_BROWSING_KEY
          valueFrom:
            secretKeyRef:
              name: kutt
              key: safe-browsing-key
        - name: IPINFO_TOKEN
          valueFrom:
            secretKeyRef:
              name: kutt
              key: ipinfo-token
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: kutt
              key: jwt-secret
        - name: MAIL_HOST
          valueFrom:
            secretKeyRef:
              name: kutt
              key: mail-host
        - name: MAIL_HOST
          valueFrom:
            secretKeyRef:
              name: kutt
              key: mail-host
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kutt
              key: mail-password
        - name: MAIL_USER
          valueFrom:
            secretKeyRef:
              name: kutt
              key: mail-user
        - name: MAIL_FROM
          valueFrom:
            secretKeyRef:
              name: kutt
              key: mail-from
        - name: RECAPTCHA_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: kutt
              key: recaptcha-secret-key
        - name: RECAPTCHA_SITE_KEY
          valueFrom:
            secretKeyRef:
              name: kutt
              key: recaptcha-site-key
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: kutt
              key: redis-host
        - name: SENTRY_PRIVATE_DSN
          valueFrom:
            secretKeyRef:
              name: kutt
              key: sentry-private-dsn
        - name: SENTRY_PUBLIC_DSN
          valueFrom:
            secretKeyRef:
              name: kutt
              key: sentry-public-dsn
