namePrefix: lingkod-
commonLabels:
  app: lingkod-kutt
  environment: production
  org: lingkod
commonAnnotations:
  com.datadoghq.ad.tags: '["service:lingkod.to", "environment:production"]'
patchesStrategicMerge:
- configMap.yaml
bases:
- ../../base
resources:
- secrets.yaml
